Traceback (most recent call last):
  File "/home/slucidi/workspace/python/konveyor/kai/kai/routes/get_incident_solutions_for_file.py", line 57, in post_get_incident_solutions_for_file
    result: UpdatedFileContent = kai_application.get_incident_solutions_for_file(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slucidi/workspace/python/konveyor/kai/kai/service/kai_application/kai_application.py", line 223, in get_incident_solutions_for_file
    raise web.HTTPInternalServerError(
aiohttp.web_exceptions.HTTPInternalServerError: Migration failed
